kevin-lee/whatsub

build.sbt
=> Fixed: release build

.github/workflows/release.yml
=> Fixed: release build - auth

build.sbt
=> Fix #75 - Missing charsets

.scripts/install-graal-macos.sh, .scripts/install-graal-ubuntu.sh, build.sbt, changelogs/0.1.1.md
=> Whatsub v0.1.1

README.md
Updated: `README.md` - temporary installation instructions
=> Updated: README.md - temporary installation instructions

cli/src/main/scala/whatsub/Whatsub.scala, cli/src/main/scala/whatsub/WhatsubError.scala
Close #79 - Add validation for duplicate src and out file paths
=> Close #79 - Add validation for duplicate src and out file paths

.github/workflows/doc-site-publish.yml, build.sbt, project/plugins.sbt
Issue #80 - Add GitHub Actions config for doc site build
=> Issue #80 - Add GitHub Actions config for doc site build

cli/src/main/scala/whatsub/WhatsubArgsParser.scala
Close #86 - Fix incorrect color in `sync --help`
=> Close #86 - Fix incorrect color in sync --help

.scripts/install-graal-macos.sh, .scripts/install-graal-ubuntu.sh, README.md, website/docs/intro.mdx, website/docs/whatsub/get-whatsub.mdx, website/docusaurus.config.js, website/package.json
Updated: Docs and install scripts with the latest version info
=> Updated: Docs and install scripts with the latest version info

website/docusaurus.config.js
=> Updated docs - add meta image

README.md, website/docs/intro.mdx, website/docs/whatsub/get-whatsub.mdx
Updated docs - hit counter badges
=> Updated docs - hit counter badges

website/package-lock.json, website/package.json
Upgraded: Docusaurus `2.0.0-beta.5` => `2.0.0-beta.6`
=> Upgraded: Docusaurus 2.0.0-beta.5 => 2.0.0-beta.6

website/src/components/HomepageFeatures.js
=> Minor fix in the doc site

build.sbt, project/plugins.sbt
Upgraded: sbt-devoops `2.6.0` => `2.10.0`
=> Upgraded: sbt-devoops 2.6.0 => 2.10.0

.github/workflows/doc-site-publish.yml
Added: `docusaurAuditFix` to doc site build
=> Added: docusaurAuditFix to doc site build

.github/workflows/doc-site-build-only.yml, project/plugins.sbt, website/docs/whatsub/get-whatsub.mdx
Updated: The doc site with a better installation instruction
=> Updated: The doc site with a better installation instruction

.scripts/install-graal-macos.sh, .scripts/install-graal-ubuntu.sh
Updated: The installation scripts with better `PATH` setup
=> Updated: The installation scripts with better PATH setup

core/src/main/scala/whatsub/parse/SmiParser.scala
Fix #98 - Blank lines in non-body tags are not handled properly
=> Fix #98 - Blank lines in non-body tags are not handled properly

build.sbt, core/src/main/scala/whatsub/charset/ConvertCharset.scala
Close #130 - Upgrade Effectie to `1.16.0`
=> Close #130 - Upgrade Effectie to 1.16.0

cli/src/main/scala/whatsub/FileF.scala, cli/src/main/scala/whatsub/Whatsub.scala, core/src/main/scala/whatsub/CanRender.scala, core/src/main/scala/whatsub/Smi.scala, core/src/main/scala/whatsub/Srt.scala, core/src/main/scala/whatsub/sync/Syncer.scala
Close #132 - Use `extension` methods with type classes
=> Close #132 - Use extension methods with type classes

project/plugins.sbt
Upgraded: sbt-devoops `2.13.0` => `2.14.0`
=> Upgraded: sbt-devoops 2.13.0 => 2.14.0

.github/dependabot.yml
Added: `dependabot.yml` for GitHub Actions
=> Added: dependabot.yml for GitHub Actions

.github/workflows/doc-site-build-only.yml, .github/workflows/doc-site-publish.yml
Updated: GitHub Actions config
=> Updated: GitHub Actions config

.scalafmt.conf
Upgraded: `.scalafmt.conf` `3.0.6` => `3.2.0`
=> Upgraded: .scalafmt.conf 3.0.6 => 3.2.0

build.sbt, cli/src/main/scala/whatsub/FileF.scala, cli/src/main/scala/whatsub/Whatsub.scala, core/src/main/scala/whatsub/Smi.scala, core/src/main/scala/whatsub/Srt.scala, core/src/main/scala/whatsub/charset/ConvertCharset.scala, core/src/main/scala/whatsub/convert/Convert.scala, core/src/main/scala/whatsub/package.scala, core/src/main/scala/whatsub/parse/SmiParser.scala, core/src/main/scala/whatsub/parse/SrtParser.scala, core/src/main/scala/whatsub/sync/Syncer.scala
`F[_]` => `F[*]` and set `-source:3.1`
=> `F[_]` => `F[*]` and set `-source:3.1`

.github/workflows/doc-site-build-only.yml, .github/workflows/doc-site-publish.yml
=> Fix: broken GitHub Actions

project/build.properties
Upgrade: sbt `1.5.5` => `1.5.8`
=> Upgrade: sbt 1.5.5 => 1.5.8

project/plugins.sbt
Upgrade: sbt-docusaur `0.8.0` => `0.8.1`
=> Upgrade: sbt-docusaur 0.8.0 => 0.8.1

website/package-lock.json, website/package.json
Upgrade: Docusaurus `2.0.0-beta.6` => `2.0.0-beta.14` / docusaurus-lunr-search `2.1.14` => `2.1.15`
=> Upgrade: Docusaurus 2.0.0-beta.6 => 2.0.0-beta.14 / docusaurus-lunr-search 2.1.14 => 2.1.15

build.sbt, cli/src/main/scala/whatsub/FileF.scala, cli/src/main/scala/whatsub/MainIo.scala, cli/src/main/scala/whatsub/Whatsub.scala, cli/src/main/scala/whatsub/WhatsubApp.scala, core/src/main/scala/whatsub/Smi.scala, core/src/main/scala/whatsub/Srt.scala, core/src/main/scala/whatsub/charset/ConvertCharset.scala, core/src/main/scala/whatsub/convert/Convert.scala, core/src/main/scala/whatsub/package.scala, core/src/main/scala/whatsub/parse/SmiParser.scala, core/src/main/scala/whatsub/parse/SrtParser.scala
Close #157 - Upgrade Effectie to `2.0.0-SNAPSHOT`
=> Close #157 - Upgrade Effectie to 2.0.0-SNAPSHOT

build.sbt
Upgrade: Scala `3.1.0` => `3.1.1`
=> Upgrade: Scala 3.1.0 => 3.1.1

core/src/main/scala/whatsub/parse/SmiParser.scala
Fix #155 - SMI `<SYNC>` having `End` attribute causes parse failure
=> Fix #155 - SMI <SYNC> having End attribute causes parse failure

build.sbt
whatsub v1.0.2 - bump the project version
=> whatsub v1.0.2 - bump the project version

.scripts/install-graal-macos.sh, .scripts/install-graal-ubuntu.sh, .scripts/install-jvm.sh
Update: The installation scripts for `v1.0.2`
=> Update: The installation scripts for v1.0.2

build.sbt, core/src/main/scala/whatsub/parse/SrtParser.scala, core/src/test/resources/golden/test-out.smi, core/src/test/resources/golden/test-out.srt, core/src/test/resources/golden/test-src.smi, core/src/test/resources/golden/test-src.srt, core/src/test/scala/whatsub/GoldenTest.scala, core/src/test/scala/whatsub/convert/ConvertSpec.scala
Close #169 - Add golden test for `Convert[F, A, B]`
=> Close #169 - Add golden test for `Convert[F, A, B]`

.scripts/install-graal-macos.sh, .scripts/install-graal-ubuntu.sh, .scripts/install-jvm.sh
Update: The installation scripts for `v1.0.3`
=> Update: The installation scripts for v1.0.3

build.sbt, changelogs/1.0.4.md
* `SmiParser` - Error when line appears after start and end (#174)
=> whatsub v1.0.4

.scripts/install-graal-macos.sh, .scripts/install-graal-ubuntu.sh, .scripts/install-jvm.sh
Update: The installation scripts for v1.0.4
=> Update: The installation scripts for v1.0.4

project/plugins.sbt
Upgrade: `sbt-devoops` `2.15.0` => `2.16.0` / `sbt-docusaur` `0.8.1` => `0.9.0`
=> Upgrade: sbt-devoops 2.15.0 => 2.16.0 / sbt-docusaur 0.8.1 => 0.9.0

cli/src/main/scala/whatsub/FileF.scala, cli/src/main/scala/whatsub/Whatsub.scala
Clean up and refactor (also fix typo)
=> Clean up and refactor (also fix typo)

.github/workflows/build-graal.yml, .github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/sbt-build-all.sh, build.sbt, core/src/main/scala/whatsub/parse/SmiParser.scala, core/src/main/scala/whatsub/parse/SrtParser.scala, project/plugins.sbt
Upgrade: sbt plugins
- sbt-docusaur 0.9.0 => 0.11.0
- sbt-devoops 2.16.0 => 2.20.0
- sbt-wartremover 3.0.0 => 3.0.4
=> Upgrade: sbt plugins

.github/workflows/build-graal.yml, .github/workflows/build.yml, .github/workflows/doc-site-build-only.yml, .github/workflows/doc-site-publish.yml, .github/workflows/release.yml, build.sbt, project/plugins.sbt
Close #185 - Upgrade Java to `17` and GraalVM native image version `22.1.0`
* Java `11` => `17`
* ~~`sbt-native-image` `0.3.0` => `0.3.2`~~
* GraalVM native image version `22.1.0`
=> Close #185 - Upgrade Java to 17 and GraalVM native image version 22.1.0

build.sbt
Close #189 - Upgrade pirate `deec3408b08a751de9b2df2d17fc1ab7b8daeaaf` => `18dfbbca014ba2312a640cf558ab6eca19c47eb8`
=> Close #189 - Upgrade pirate deec3408b08a751de9b2df2d17fc1ab7b8daeaaf => 18dfbbca014ba2312a640cf558ab6eca19c47eb8

cli/src/main/scala/whatsub/Whatsub.scala
Close #192 - Add success message for charset conversion
=> Close #192 - Add success message for charset conversion

cli/src/main/scala/whatsub/FileF.scala, cli/src/main/scala/whatsub/Whatsub.scala
Close #195 - Highlight the result message and file path with color
=> Close #195 - Highlight the result message and file path with color

.github/workflows/checks.yml, .scalafix.conf, core/src/main/scala/whatsub/charset/package.scala, project/plugins.sbt
Close #199 - Add Scalafix and Scalafmt
=> Close #199 - Add Scalafix and Scalafmt

build.sbt
Close #201 - Upgrade `cats` `2.7.0` => `2.8.0`
=> Close #201 - Upgrade cats 2.7.0 => 2.8.0

build.sbt, project/plugins.sbt
Upgrade: Scala `3.1.2` => `3.1.3` and sbt plugins
=> Upgrade: Scala `3.1.2` => `3.1.3` and sbt plugins

.scripts/install-graal-macos.sh, .scripts/install-graal-ubuntu.sh, .scripts/install-jvm.sh, website/docs/intro.mdx, website/docs/whatsub/get-whatsub.mdx
Update: docs and installation scripts
=> Update: docs and installation scripts

.scalafix.conf, cli/src/main/scala/whatsub/FileF.scala, cli/src/main/scala/whatsub/Whatsub.scala, cli/src/main/scala/whatsub/WhatsubArgs.scala, cli/src/main/scala/whatsub/WhatsubArgsParser.scala, cli/src/main/scala/whatsub/WhatsubError.scala, core/src/main/scala/whatsub/typeclasses/CanBeString.scala, core/src/test/scala/whatsub/GoldenTest.scala
=> Explicit null handling

build.sbt
Upgrade: GraalVM `22.1.0` => `22.2.0`
=> Upgrade: GraalVM 22.1.0 => 22.2.0

project/plugins.sbt
Upgrade: `sbt-scalafix` `0.10.1` => `0.10.3`
=> Upgrade: sbt-scalafix 0.10.1 => 0.10.3

.github/workflows/build-graal.yml, .github/workflows/build.yml, .github/workflows/release.yml, build.sbt, modules/whatsub-cli/src/main/scala/whatsub/FileF.scala, modules/whatsub-cli/src/main/scala/whatsub/MainIo.scala, modules/whatsub-cli/src/main/scala/whatsub/Whatsub.scala, modules/whatsub-cli/src/main/scala/whatsub/WhatsubApp.scala, modules/whatsub-core/src/test/scala/whatsub/convert/ConvertSpec.scala, project/ProjectInfo.scala, project/plugins.sbt
Close #218 - Upgrade `effectie` to `2.0.0-beta2`
=> Close #218 - Upgrade `effectie` to `2.0.0-beta2`

project/plugins.sbt
Upgrade sbt-plugins
- sbt-docusaur 0.11.0 => 0.12.0
- sbt-devoops 2.22.0 => 2.23.0
=> Upgrade sbt-plugins

project/build.properties, project/plugins.sbt
=> Bump sbt `1.7.2` => `1.8.0`

project/build.properties
=> Bump sbt 1.8.0 => 1.8.2

project/plugins.sbt
Bump sbt-devoops 2.23.0 => 2.24.0 / sbt-docusaur 0.12.0 => 0.13.0
=> Bump sbt-devoops 2.23.0 => 2.24.0 / sbt-docusaur 0.12.0 => 0.13.0

.scalafmt.conf, modules/whatsub-cli/src/main/scala/whatsub/WhatsubArgs.scala
Update: `.scalafmt.conf` - `3.4.3` => `3.7.1` / remove align for `:=`
=> Update: `.scalafmt.conf` - `3.4.3` => `3.7.1` / remove align for `:=`

build.sbt, project/plugins.sbt
Update sbt plugins
- Bump sbt-wartremover `3.0.7` => `3.0.9`
- Add sbt-tpolecat `0.4.2`
=> Update sbt plugins

.scripts/install-graal-macos.sh, .scripts/install-graal-ubuntu.sh, .scripts/install-jvm.sh
Update: Installation scripts - `install-graal-macos.sh`, `install-graal-ubuntu.sh` and `install-jvm.sh`
=> Update: Installation scripts - `install-graal-macos.sh`, `install-graal-ubuntu.sh` and `install-jvm.sh`

website/docs/whatsub/get-whatsub.mdx
Update: docs with the latest version (1.2.0)
=> Update: docs with the latest version (1.2.0)

build.sbt, modules/whatsub-cli/src/main/scala/whatsub/MainIo.scala, modules/whatsub-cli/src/main/scala/whatsub/Whatsub.scala, modules/whatsub-core/src/main/scala/whatsub/FileF.scala
Upgrade libraries
- effectie to `2.0.0-beta9`
- extras to `0.38.0`
- Update the code accordingly
=> Upgrade libraries

project/plugins.sbt
Upgrade plugin
- `sbt-wartremover` to `3.1.0`
=> Upgrade plugin

project/build.properties
=> Upgrade sbt 1.8.2 => 1.8.3

.github/workflows/build-graal.yml, .github/workflows/build.yml, .github/workflows/release.yml, build.sbt
Upgrade: Scala and GraalVM
- Scala to 3.3.0
- GraalVM to 22.3.0
=> Upgrade: Scala and GraalVM

modules/whatsub-core/src/main/scala/whatsub/Playtime.scala, modules/whatsub-core/src/main/scala/whatsub/Smi.scala, modules/whatsub-core/src/main/scala/whatsub/Srt.scala
Add targetName to infix operator methods
=> Add targetName to infix operator methods

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/task-template.md, .scripts/install-graal-macos.sh, .scripts/install-graal-ubuntu.sh, .scripts/install-jvm.sh, README.md, build.sbt, changelogs/0.1.0.md, changelogs/0.1.1.md, changelogs/0.1.2.md, changelogs/0.1.3.md, changelogs/1.0.0.md, changelogs/1.0.1.md, changelogs/1.0.2.md, changelogs/1.0.3.md, changelogs/1.0.4.md, changelogs/1.1.0.md, changelogs/1.2.0.md, changelogs/1.2.1.md, website/docs/intro.mdx, website/docs/whatsub/get-whatsub.mdx, website/docusaurus.config.js
Update: GitHub username - Kevin-Lee => kevin-lee
=> Update: GitHub username - Kevin-Lee => kevin-lee

project/build.properties
=> Bump sbt to 1.9.0

build.sbt, project/build.properties
=> Bump sbt to 1.9.1

.scalafmt.conf
=> Bump scalafmt to `3.7.5`

.github/workflows/build-graal.yml, .github/workflows/build.yml, .github/workflows/checks.yml, .github/workflows/release.yml
- Fix `JVM_OPTS` and `SBT_OPTS`
- Add `-XX:+UseG1GC`
- Change `-Xms1024m` to `-Xms2G`
=> Fix Java options passed to sbt

.github/workflows/build-graal.yml, .github/workflows/build.yml, .github/workflows/checks.yml, .github/workflows/release.yml, project/build.properties
=> Bump sbt to `1.9.4`

.github/workflows/build-graal.yml, .github/workflows/build.yml, .github/workflows/checks.yml, .github/workflows/doc-site-build-only.yml, .github/workflows/doc-site-publish.yml, .github/workflows/release.yml
Upgrade: `actions/cache` from `v4.1.1` to `v4` in workflow files
=> Upgrade: `actions/cache` from `v4.1.1` to `v4` in workflow files

.github/workflows/build-graal.yml, .github/workflows/build.yml, .github/workflows/release.yml, build.sbt, modules/whatsub-ai/src/main/scala/whatsub/ai/translate/Translator.scala, modules/whatsub-ai/src/test/scala/whatsub/ai/translate/Gens.scala, modules/whatsub-ai/src/test/scala/whatsub/ai/translate/TranslatorSpec.scala, modules/whatsub-cli/src/main/scala/whatsub/MainIo.scala, modules/whatsub-cli/src/main/scala/whatsub/Whatsub.scala, modules/whatsub-cli/src/main/scala/whatsub/WhatsubArgs.scala, modules/whatsub-cli/src/main/scala/whatsub/WhatsubArgsParser.scala, modules/whatsub-cli/src/main/scala/whatsub/WhatsubError.scala, modules/whatsub-core/src/main/scala/whatsub/FileF.scala, modules/whatsub-core/src/main/scala/whatsub/Srt.scala, modules/whatsub-core/src/main/scala/whatsub/charset/CharsetConvertError.scala, modules/whatsub-core/src/main/scala/whatsub/package.scala, modules/whatsub-core/src/main/scala/whatsub/parse/ParseError.scala, modules/whatsub-core/src/main/scala/whatsub/parse/SmiParser.scala, modules/whatsub-core/src/main/scala/whatsub/parse/SrtParser.scala, modules/whatsub-core/src/main/scala/whatsub/typeclasses/Scala3TypeClasses.scala, modules/whatsub-core/src/test/scala/whatsub/GoldenTest.scala, modules/whatsub-core/src/test/scala/whatsub/convert/ConvertSpec.scala, modules/whatsub-core/src/test/scala/whatsub/parse/ParserGoldenTester.scala, modules/whatsub-core/src/test/scala/whatsub/parse/SrtParserSpec.scala, project/plugins.sbt
Update `build.sbt` with new versions for `Scala`, `effectie`, `logger-f`, `openai4s` and sbt plugin
- Update Scala to 3.3.5
- Update effectie to 2.0.0
- Update logger-f to 2.1.8
- Update openai4s to 0.1.0-alpha13
- Add refined4s 1.1.0
- sbt-wartremover to 3.3.2
- sbt-devoops to 3.2.0
- sbt-docusaur to 0.17.0
Also fix the broken code caused by Scala, libraries and sbt plugin bumping
=> Update `build.sbt` with new versions for `Scala`, `effectie`, `logger-f`, `openai4s` and sbt plugin

README.md, website/docs/intro.mdx
Update hit counter badge to use hits.sh
=> Update hit counter badge to use hits.sh

website/src/pages/index.js
Add hidden tracking image to hero banner
=> Add hidden tracking image to hero banner

.github/workflows/build-graal.yml
Update GitHub Actions: use `actions/setup-java` and `sbt/setup-sbt`
=> Update GitHub Actions: use `actions/setup-java` and `sbt/setup-sbt`

.github/workflows/build.yml
Update GitHub Actions: build.yml - use `actions/setup-java` and `sbt/setup-sbt`
=> Update GitHub Actions: build.yml - use `actions/setup-java` and `sbt/setup-sbt`

.github/workflows/checks.yml
Update GitHub Actions: `checks.yml` - use `actions/setup-java` and `sbt/setup-sbt`
=> Update GitHub Actions: `checks.yml` - use `actions/setup-java` and `sbt/setup-sbt`

.github/workflows/doc-site-build-only.yml
Update GitHub Actions: `doc-site-build-only.yml` - use `actions/setup-java` and `sbt/setup-sbt`
=> Update GitHub Actions: `doc-site-build-only.yml` - use `actions/setup-java` and `sbt/setup-sbt`

.github/workflows/doc-site-publish.yml
Update GitHub Actions: `doc-site-publish.yml` - use `actions/setup-java` and `sbt/setup-sbt`
=> Update GitHub Actions: `doc-site-publish.yml` - use `actions/setup-java` and `sbt/setup-sbt`

.github/workflows/build-graal.yml, .github/workflows/release.yml, .scripts/install-graal-macos.sh
Fix #297 - Installation script may not work on the latest macOS
- Also improve the installation script for macOS to support multiple macOS versions
=> Fix #297 - Installation script may not work on the latest macOS

changelogs/1.2.2.md
* Installation script may not work on the latest macOS (#297)
=> whatsub v1.2.2

.scripts/install-graal-macos.sh, .scripts/install-graal-ubuntu.sh, .scripts/install-jvm.sh
Fix the installation scripts and bump the app version to 1.2.2
=> Fix the installation scripts and bump the app version to 1.2.2

.github/workflows/build-graal.yml, .github/workflows/build.yml, .github/workflows/release.yml, build.sbt, modules/whatsub-cli/src/main/scala/whatsub/WhatsubArgsParser.scala, project/plugins.sbt
=> Bump Scala to 3.3.6

build.sbt
Bump libraries
* logger-f: 2.2.0 -> 2.4.0
* refined4s: 1.10.0 -> 1.11.0
=> Bump libraries
