kevin-lee/whatsub

core/src/main/scala/whatsub/parse/ParseError.scala, core/src/main/scala/whatsub/parse/SrtComponent.scala, core/src/main/scala/whatsub/parse/SrtParser.scala
Fix #82 - Parsing SRT fails when line contains only a number
=> Fix #82 - Parsing SRT fails when line contains only a number

build.sbt, changelogs/0.1.2.md
* Add validation for duplicate `src` and `out` filenames (#79)
* Create the doc site (#80)
* Parsing `SRT` fails when line contains only a number (#82)
* Fix incorrect color in `sync --help` (#86)
=> Whatsub v0.1.2

build.sbt, changelogs/0.1.3.md
* Blank lines in non-body tags are not handled properly (#98)
=> whatsub v0.1.3

cli/src/main/scala/whatsub/WhatsubArgsParser.scala
Close #106 - Simplify options - Get rid of `--src` and `--out`
=> Close #106 - Simplify options - Get rid of --src and --out

.github/pr-labeler.yml
Update: PR labeler - `documentation` and `publish-docs`
=> Update: PR labeler - documentation and publish-docs

changelogs/1.0.2.md
* SMI `<SYNC>` having `End` attribute causes a parse failure (#155)
* `SmiParser` - Having comment inside `<BODY>` causes a parse error (#159)
* Upgrade Scala to `3.1.0` (#128)
* Upgrade Effectie to `1.16.0` (#130)
* Upgrade Effectie to `2.0.0-SNAPSHOT` (#157)
* Use `extension` methods with type classes (#132)
=> whatsub v1.0.2

project/build.properties, project/plugins.sbt
Upgrade: sbt and plugins
- sbt 1.6.1 => 1.6.2
- sbt-native-packager 1.9.4 => 1.9.9
- sbt-buildinfo 0.10.0 => 0.11.0
- sbt-devoops 2.14.0 => 2.15.0
=> Upgrade: sbt and plugins

core/src/main/scala/whatsub/parse/SmiParser.scala
Fix #167 - Comment in the middle or line start and end make `SmiParser` skip the line
=> Fix #167 - Comment in the middle or line start and end make SmiParser skip the line

build.sbt, changelogs/1.0.3.md
* A comment between line start and end makes `SmiParser` skip the line (#167)
* Add golden test for `Convert[F, A, B]` (#169)
=> whatsub v1.0.3

core/src/main/scala/whatsub/parse/ParseError.scala, core/src/main/scala/whatsub/parse/SmiParser.scala, core/src/test/resources/golden/test-src.smi
Fix #174 - `SmiParser` - Error when line appears after start and end
=> Fix #174 - SmiParser - Error when line appears after start and end

build.sbt, project/plugins.sbt
Close #187 - Upgrade libraries
* `hedgehog` `0.8.0` => `0.9.0`
* `cats-effect` `3.3.6` => `3.3.12`
* `cats-parse` `0.3.4` => `0.3.7`
* `effectie-cats-effect3` `2.0.0-SNAPSHOT` => `2.0.0-beta1`
* `extras-cats` and `extras-scala-io` `0.4.0` => `0.15.0`
* `sbt-devoops` `2.20.0` => `2.21.0`
=> Close #187 - Upgrade libraries

cli/src/main/scala/whatsub/FileF.scala, cli/src/main/scala/whatsub/Whatsub.scala, cli/src/main/scala/whatsub/WhatsubError.scala, core/src/main/scala/whatsub/charset/ConvertCharset.scala
Close #197 - Make `FileF.writeFile` more reusable with a function using `Writer`
=> Close #197 - Make `FileF.writeFile` more reusable with a function using `Writer`

.scripts/install-graal-macos.sh, .scripts/install-graal-ubuntu.sh, .scripts/install-jvm.sh, build.sbt, changelogs/1.1.0.md
* Add success message for charset conversion (#192)
* Highlight the result message and file path with color (#195)
* Make `FileF.writeFile` more reusable with a function using `Writer` (#197)
* Upgrade Java to `17` and GraalVM native image version `22.1.0` (#185)
* Set up `WartRemover` for Scala 3 (#180)
* Upgrade libraries (#187)
* `hedgehog` `0.8.0` => `0.9.0`
* `cats-effect` `3.3.6` => `3.3.12`
* `cats-parse` `0.3.4` => `0.3.7`
* `effectie-cats-effect3` `2.0.0-SNAPSHOT` => `2.0.0-beta1`
* `extras-cats` and `extras-scala-io` `0.4.0` => `0.15.0`
* `sbt-devoops` `2.20.0` => `2.21.0`
* Upgrade `pirate` (#189) - `deec3408b08a751de9b2df2d17fc1ab7b8daeaaf` => `18dfbbca014ba2312a640cf558ab6eca19c47eb8`
* Upgrade `cats` `2.7.0` => `2.8.0` (#201)
* Add Scalafix and Scalafmt (#199)
=> whatsub v1.1.0

build.sbt
Upgrade: Scala and libraries
- Scala `3.1.3` => `3.2.0`
- cats-effect `3.3.12` => `3.3.14`
- cats-parse `0.3.7` => `0.3.8`
- extras `0.15.0` => `0.19.0`
=> Upgrade: Scala and libraries

build.sbt, modules/whatsub-cli/src/main/scala/whatsub/FileF.scala, modules/whatsub-cli/src/main/scala/whatsub/MainIo.scala, modules/whatsub-cli/src/main/scala/whatsub/Whatsub.scala, modules/whatsub-cli/src/main/scala/whatsub/WhatsubApp.scala, modules/whatsub-core/src/test/scala/whatsub/convert/ConvertSpec.scala, project/plugins.sbt
Closea #226 - Bump Scala and libraries
* Scala 3.2.0 => 3.2.1
* Cats 2.8.0 => 2.9.0
* Cats Effect 3.3.14 => 3.4.1
* Effectie 2.0.0-beta2 => 2.0.0-beta3
* Extras 0.19.0 => 0.25.0
* Pirate 18dfbbca014ba2312a640cf558ab6eca19c47eb8 => 7797fb3884bdfdda7751d8f75accf622b30a53ed
=> Closea #226 - Bump Scala and libraries

build.sbt
Close #235 - Upgrade libraries
* `hedgehog` to `0.10.1`
* `cats-effect` to `3.4.6`
* `cats-parse` to `0.3.9`
* `effectie` to `2.0.0-beta5`
* `extras` to `0.29.0`
=> Close #235 - Upgrade libraries

build.sbt, changelogs/1.2.0.md, version.sbt
* SRT: double lines are not parsed properly (#237)
* Move sub-projects to modules (#210)
* Upgrade GraalVM to `22.2.0` (#213)
* Upgrade Scala and libraries (#218) (#226) (#235)
* Scala to `3.2.1`
* cats to `2.9.0`
* cats-effect to `3.4.6`
* cats-parse to `0.3.9`
* effectie to `2.0.0-beta6`
* extras to `0.30.0`
* pirate to `7797fb3884bdfdda7751d8f75accf622b30a53ed`
* hedgehog to `0.10.1`
=> whatsub v1.2.0

build.sbt
Upgrade Scala and libraries
- Scala to `3.2.2`
- `cats-effect` to `3.4.8`
- `effectie` to `2.0.0-beta7`
- `extras` to `0.32.0`
=> Upgrade Scala and libraries

.scripts/install-graal-macos.sh, .scripts/install-graal-ubuntu.sh, .scripts/install-jvm.sh, changelogs/1.2.1.md, version.sbt
* Parsing SAMI file fails when there's no `<TITLE>` tag (#252)
* Upgrade Scala and libraries
* Scala to `3.2.2`
* cats-effect to `3.4.8`
* effectie to `2.0.0-beta9`
* extras to `0.38.0`
* sbt-wartremover to `3.1.0`
=> whatsub v1.2.1

.github/workflows/build-graal.yml, .github/workflows/release.yml
Fix GitHub Actions build for Windows - Resize JVM memory setup
* Based on the following reference:
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
=> Fix GitHub Actions build for Windows - Resize JVM memory setup
